
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/\u041d\u0438\u043a\u043e\u043b\u0430\u0439/downloads/cmake-4.0.3-windows-x86_64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
